options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy authCallback
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy authCallback \
          --runtime=nodejs20 \
          --trigger-http \
          --region=europe-west2 \
          --allow-unauthenticated \
          --entry-point=authCallback \
          --source=. \
          --gen2 \
          --service-account=flair-december-2024@appspot.gserviceaccount.com

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy adminDashboard
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy adminDashboard \
          --runtime=nodejs20 \
          --trigger-http \
          --region=europe-west2 \
          --allow-unauthenticated \
          --entry-point=adminDashboard \
          --source=. \
          --gen2 \
          --service-account=flair-december-2024@appspot.gserviceaccount.com

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy FreeAgent
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy FreeAgent \
          --runtime=nodejs20 \
          --trigger-http \
          --region=europe-west2 \
          --allow-unauthenticated \
          --entry-point=FreeAgent \
          --source=. \
          --gen2 \
          --service-account=flair-december-2024@appspot.gserviceaccount.com