options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy authCallback \
          --runtime=nodejs20 \
          --trigger-http \
          --region=global \
          --allow-unauthenticated \
          --source=. \
          --entry-point=authCallback \
          --service-account=flair-december-2024@appspot.gserviceaccount.com